name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # This will trigger the workflow on a push to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      # Tag the Docker image for ECR
      - name: Tag Docker Image
        run: |
          docker tag my-app:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest

      # Push the Docker image to ECR
      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest
